# Site setings
name:             'Waves'
description:      'C/C++, SLAM, Computer vision'
meta_description: 'bada'
logo:
author:
  image:          'assets/images/authorimage.jpg'
  greetings:      "일상 기록"
favicon:          'assets/images/logo_wave.ico'

# Contact form setings
#email: \<first-name\>_\<last-name\>@email.com
#contact_page_description: "Get in contact with me!"
#thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
github:   'Wonmyung'
linkedin: 'Wonmyung Lee'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Daily record
    url: /experience
  - text: Computer vision
    url: /projects
  - text: Software
    url: /experience

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
